import = [
  "C:\\Users\\samsu\\AppData\\Roaming\\alacritty\\base.toml",

  # Themes
  # "~\\AppData\\Roaming\\alacritty\\colors_Dracula.toml",
  # "~\\AppData\\Roaming\\alacritty\\dracula.toml",
  "~\\AppData\\Roaming\\alacritty\\nightfox.toml",
  # "~\\AppData\\Roaming\\alacritty\\catppuccin-mocha.toml",
  # "~\\AppData\\Roaming\\alacritty\\catppuccin-frappe.toml",
  # "~\\AppData\\Roaming\\alacritty\\catppuccin-macchiato.toml",
]
