# shell = { program = "powershell" }
terminal.shell = { program = "ubuntu" }

# working_directory = "C:\\"
general.live_config_reload = true
# draw_bold_text_with_bright_colors = true
#
# [shell]
  # program = "C:\\Windows\\system32\\cmd.exe"
  # program = "powershell"




[font]
  # normal = { family = "Hack NF", style = "Regular" }
  # bold = { family = "Hack NF", style = "Bold" }
  # italic = { family = "Hack NF", style = "Italic" }
  # bold_italic = { family = "Hack NF", style = "Bold Italic" }

  normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
  italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
  bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
  size = 14.00

[window]
  position = { x = 50, y = 30 }
  
  dimensions = { columns = 100, lines = 35 }
  padding = { x = 10, y = 10 }



  # Startup Mode (changes require restart)
  startup_mode = "Windowed"
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations = "full"
  # opacity = 0.95

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
# custom_cursor_colors = "true"

# colors:
#  primary:
#    background: "#1e2127"
#    foreground: "#D8DEE9"




[scrolling]
  history = 10000
  multiplier = 10

[cursor]
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style = { shape = "Underline", blinking = "On" }
  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift",  action = "Paste"},
  { key = "V",        mods = "Control",        action = "Paste"},
  { key = "C",        mods = "Control|Shift",  action = "Copy"},
  { key = "C",        mods = "Control",        action = "Copy"},
  { key = "N",        mods = "Command",        action = "SpawnNewInstance"},
  { key = "Q",        mods = "Alt",            action = "Quit"},
  { key = "Return",   mods = "Alt",            action = "ToggleFullscreen"},
  { key = "Plus",     mods = "Control",        action = "IncreaseFontSize"},
  { key = "Minus",    mods = "Control",        action = "DecreaseFontSize"},
  { key = "Key0",     mods = "Control",        action = "ResetFontSize"},
  ]

[mouse]
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  # double_click = { threshold = "300" }
  # triple_click = { threshold = "300" }

  # If this is `true`, the cursor is temporarily hidden when typing.
  # hide_when_typing = true

[selection]
  semantic_escape_chars = ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard = true
